# Generated by Django 5.2.6 on 2025-10-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
