# Generated by Django 5.2.6 on 2025-11-22 19:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
