# Generated by Django 5.2.6 on 2025-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_comment_is_reported_comment_report_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the article content.', null=True),
        ),
    ]
