# Generated by Gemini

from django.db import migrations

def add_site_data(apps, schema_editor):
    # This migration previously contained data operations that could overwrite
    # production settings. It has been modified to be a no-op.
    # The management command 'ensure_site' is the correct way to manage site data.
    pass

def remove_site_data(apps, schema_editor):
    # This function is the reverse of the above, and is also a no-op.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(add_site_data, remove_site_data),
    ]