# Generated by Django 5.2.6 on 2025-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_profile_referral_code_profile_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='event_posters/')),
                ('caption', models.TextField()),
                ('event_date', models.DateField()),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
