# Generated by Django 5.2.6 on 2025-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='field_or_industry',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
