# Generated by Django 5.2.6 on 2026-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='was_shared_on_whatsapp',
            field=models.BooleanField(default=False, help_text='Tracks if this article has been shared on WhatsApp.'),
        ),
    ]
