# Generated by Django 5.2.6 on 2025-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_contributor_field_or_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='field_or_industry',
            field=models.CharField(max_length=100),
        ),
    ]
