# Generated by Django 5.2.6 on 2026-03-11 09:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_article_was_shared_on_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='whatsapp_covers/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('short_description', models.TextField(blank=True, help_text='A short snippet for social previews.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('was_shared_on_whatsapp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'WhatsApp Update',
                'verbose_name_plural': 'WhatsApp Updates',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
