# Generated by Django 5.2.6 on 2026-03-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_whatsappupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(help_text='Note: PDFs should be less than 30 MBs.', upload_to='pdfs/'),
        ),
    ]
