# Generated by Django 5.2.6 on 2026-01-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_contributor_field_or_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short professional summary.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, help_text='Where you work or represent.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, help_text='Your field or industry.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, choices=[('student', 'Student/Intern'), ('entry', 'Entry Level'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'VP/Head of Department'), ('c_suite', 'C-Suite (CEO, CFO, etc.)'), ('founder', 'Founder/Owner'), ('consultant', 'Consultant/Freelancer'), ('other', 'Other')], help_text='Your level or capacity within the organization.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Your current professional position.', max_length=100),
        ),
    ]
