# Generated by Django 5.2.6 on 2026-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_profile_bio_profile_company_profile_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
