# Generated by Django 5.2.6 on 2026-01-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_alter_magazine_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
