# Generated by Django 5.2.6 on 2026-03-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_add_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='publications.article'),
        ),
        migrations.AlterField(
            model_name='whatsappupdate',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
