# Generated by Django 5.2.6 on 2026-01-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributor',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
