# Generated by Django 5.2.6 on 2026-03-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_alter_magazine_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magazine',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Newsletter subscription status.'),
        ),
    ]
