# Generated by Django 5.2.6 on 2026-01-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_contributor_has_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='has_account',
        ),
    ]
