# Generated by Django 5.2.6 on 2026-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_automation_enabled', models.BooleanField(default=False, help_text='Global toggle for all automated emails (digests and welcome emails). If OFF, only manual triggers from Admin will work.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
