# Generated by Django 5.2.6 on 2026-03-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_securityconfiguration_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
