# Generated by Django 5.2.6 on 2026-03-29 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_alter_securityevent_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Homepage Hero', max_length=100)),
                ('slot_name', models.CharField(help_text='The div ID or slot name (e.g., div-gpt-ad-hero).', max_length=100, unique=True)),
                ('gam_id', models.CharField(help_text='Full GAM path (e.g., /12345/Article_Mid).', max_length=255)),
                ('sizes', models.CharField(default='[[728, 90]]', help_text='GPT sizes array (e.g., [[728, 90], [320, 50]]).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ad Unit',
                'verbose_name_plural': 'Ad Units',
            },
        ),
        migrations.CreateModel(
            name='HouseAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='house_ads/')),
                ('link_url', models.URLField(help_text='Where the ad should link to.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_ads', to='publications.adunit')),
            ],
            options={
                'verbose_name': 'House Ad',
                'verbose_name_plural': 'House Ads',
            },
        ),
    ]
