# Generated by Django 5.2.6 on 2026-07-15 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_adunit_housead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date/time shown to users.'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date/time shown to users (determines the displayed month).'),
        ),
    ]
