# Generated by Django

from django.db import migrations, models
import uuid  # <-- Import uuid

def gen_uuid(apps, schema_editor):
    """
    A special function to manually generate a unique UUID for each existing Profile.
    """
    Profile = apps.get_model('publications', 'Profile')
    for row in Profile.objects.all():
        row.referral_code = uuid.uuid4()
        row.save(update_fields=['referral_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_profile'), #<-- Make sure this matches the previous migration file number
    ]

    operations = [
        # 1. Add the field but allow it to be null temporarily
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.UUIDField(null=True, unique=True),
        ),
        # 2. Run our special function to populate unique UUIDs for existing rows
        migrations.RunPython(gen_uuid),
        
        # 3. Alter the field to use the default and make it non-nullable
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        
        # This part for referred_by is fine and does not need changes
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='referrals', to='auth.user'),
        ),
    ]